### ISSUE TITLE
Can't open bookmarks, even with Telescope and all installed?

### ISSUE THREAD

**Issue by tdoerrich** [lifer0se/ezbookmarks.nvim#1]
Hello, 
I've been trying to use this plugin but I can't get it working. 

```
map ('n', '<leader>bf', 'lua require"ezbookmarks".AddBookmark()')
map ('n', '<leader>bd', 'lua require"ezbookmarks".AddBookmarkDirectory()')
map ('n', '<leader>bb', 'lua require"ezbookmarks".OpenBookmark()')

```
I added those to my shortcuts, but I don't see any response from any of them and nothing that opens in Telescope. Am I missing something?

**Comment by lifer0se** [comment]
Try adding `<cmd>` or ` : ` before `lua` like so:

`map ('n', '<leader>bf', '<cmd>lua require"ezbookmarks".AddBookmark()')`

Let me know if that works.

**Comment by tdoerrich** [comment]
> Try adding `<cmd>` or `:` before `lua` like so:
> 
> `map ('n', '<leader>bf', '<cmd>lua require"ezbookmarks".AddBookmark()')`
> 
> Let me know if that works.

Yep! That seems to have fixed it. :) Now something opens in Telescope on the last command. 

However, it is empty even after adding a file or directory to my bookmarks list. Is there any file I look if they are there in?

![image](https://user-images.githubusercontent.com/5912371/144885376-aa159d52-2083-4670-a239-8adf429dc4fa.png)

**Comment by lifer0se** [comment]
The plugin generates the file $HOME/.local/share/nvim/ezbookmarks.txt. (It just saves the paths in there, nothing fancy. Directories should have a slash at the end, that's all.) The directory is sources using the `vim.fn.stdpath('data')` command.

Have a look and see if the file is generated. If it's not there, try and see what `:lua print(vim.fn.stdpath('data'))` prints to the cmdline and let me know.

**Comment by tdoerrich** [comment]
So I have paths in there, but they none of them show up. I'm on Windows if that makes a difference.

**Comment by lifer0se** [comment]
Oh that should be it. I've only tested this on linux. 

I'll have a look after work, I'll need to spin up an old windows laptop. 

I'll let you know after I check.

**Comment by lifer0se** [comment]
Latest commit should fix the issue. Give it a shot and let me know.

**Comment by tdoerrich** [comment]
I updated the plugin but still have some issues.

1. When I add a single file now it shows up in telescope, but I get an error when wanting to  open it
![image](https://user-images.githubusercontent.com/5912371/144989606-7383382a-7ada-45f8-8b5d-a67921a1bf91.png)

2. Directories still does not show up in any way or form
D:\Projects\unity3d\Assets\Scripts/ - _The last slashes also go in a different direction, I tried manually updating these but that didn't fix the issue either._
C:\Users\PC Home\AppData\Local\nvim/
C:\Users\PC Home\AppData\Local\nvim\init.lua - This one works, but I can't open it like mentioned above.

Sorry, I feel like I'm just breaking stuff because I'm on Windows (which is true actually), and I wish I didn't have to be on Windows but for my work I have too. :(

**Comment by lifer0se** [comment]
> Sorry, I feel like I'm just breaking stuff because I'm on Windows (which is true actually), and I wish I didn't have to be on Windows but for my work I have too. :(

That's quite alright! The more reliable this is the happier I'll be :)

I'll get it working within the day and let you know!

**Comment by lifer0se** [comment]
That should now be fixed. Have a look and let me know.

I'll be adding a few improvements in the next few days. Stuff that I came up with while working on windows for the plugin.
For example, some paths are too long and are not legible, I'll use some more of telescope's features to decrease the size of the paths in the list and add external options so people can tweak telescope.

I was thinking of integrating the plugin to the telescope extensions, but I'll most likely keep it as is so I can add support for fzf as well.

**Comment by tdoerrich** [comment]
Yes! Seems to work now for me! Thank you for being so quick with a fix! :)

**Comment by lifer0se** [comment]
Let me know if you find any other windows related issues. 

Suggestions for improvements are also welcome :)
